Feature/merchant create product
TreinaDev/e-commerce-td08-time03 pull request #10
Opened 2022-06-08 23:25 UTC by fmarga

Cria funcionalidade de cadastrar produto com situação de sucesso e falha

2022-06-09 11:58 UTC, OtavioLins commented
Gente, comentei ali em cima várias coisas, mas também tem a questão de que como o login não foi mergeado ainda vocês vão ter que atualizar para proteger esse fluxo, certo? Daí vocês já aproveitam e vão fazendo esses ajustes que eu comentei :)

2022-06-09 12:24 UTC, marcuxyz commented on spec/system/merchant_creates_product_model_spec.rb
> +    expect(page).to have_content 'Informe as caracteristicas do produto'
Sentir falta de uma expectativa para verificar o preço do produto :)

2022-06-09 12:55 UTC, akaninja requested changes
Está ficando bacana! Deixei alguns comentário para ir ajustando. Uma coisa legal que podem fazer quando abrirem um MR é incluir prints das telas pra gente poder ver como está ficando. Mais pra saber como as telas estão montadas, não pra avaliar a estética.

2022-06-09 12:55 UTC, akaninja commented on spec/factories/product_models.rb
> +    length { 1.5 }
Quando usamos FactoryBot é uma boa prática inserir dados que simulem a realidade dentro da factory, assim a gente evita possíveis problemas nos testes. Por exemplo, digamos que o teste usa a factory para criar um `product_model` e renderiza na tela os seus dados, mas sua expectativa do teste busca por um outro campo de outro modelo, que por acaso também ficou "MyString". Isso pode gerar um falso positivo, já que tudo está configurado como "MyString" por padrão.

2022-06-09 20:54 UTC, fmarga commented on spec/system/merchant_creates_product_model_spec.rb
> +  end
Teste removido

2022-06-09 20:57 UTC, fmarga commented on spec/factories/product_models.rb
> +    length { 1.5 }
Quando executamos bundle install o FactoryBot foi configurado, porém não havíamos percebido que a gem já estava inclusa no Gemfile, então foi criado automaticamente esse arquivo para o model. Configuramos a gem e agora está tudo certo

2022-06-10 11:51 UTC, OtavioLins approved these changes

2022-06-10 11:51 UTC, OtavioLins commented on spec/system/product_model/merchant_creates_product_model_spec.rb
> +end
E ah, isso aqui é bem pequeno, mas seria legal apagar esses espaços em branco entre os dois 'end' :)

2022-06-10 11:51 UTC, OtavioLins commented on app/controllers/product_models_controller.rb
> +end
Aqui também, duas linhas em branco desnecessárias

2022-06-10 12:18 UTC, akaninja approved these changes

2022-06-10 12:19 UTC, akaninja commented on spec/system/product_model/merchant_creates_product_model_spec.rb
> +  end
Entendo o objetivo desse teste, mas o teste abaixo já faz a verificação da presença dos campos quando executa o `fill_in`, então acaba sendo desnecessário ter um teste "repetido".

2022-06-10 12:24 UTC, akaninja commented
Uma prática legal é incluir na descrição quando novas gems são adicionadas ao projeto, assim a gente já sabe o que esperar antes de começar a olhar o código. Além disso, nesse caso talvez fosse interessante comentar que não foi implementada nenhuma classe de usuário/admin/etc, e por isso não tem validação, mas que isso deve ser feito futuramente. A gente deduziu que vai ser feito no futuro, mas é bom indicar esse tipo de informação.

2022-06-10 20:25 UTC, gabdemiranda approved these changes

2022-06-10 20:48 UTC, merged