refactor: adiciona opçao de limpar carrinho e complementa testes de requisição para product item
TreinaDev/e-commerce-td08-time03 pull request #58
Opened 2022-06-25 01:52 UTC by fmarga

Co-Authored-By: Raifc <raif.si@hotmail.com>

Refatora carrinho de compras, adicionando botão de adicionar/remover quantidade de itens de um produto já na página do carrinho, além de criar a opção de limpar carrinho

2022-06-25 19:34 UTC, lucascda requested changes
Fiz alguns comentários, se sintam livres pra alterar se acharem conveniente

2022-06-25 19:34 UTC, lucascda commented on spec/models/product_price_spec.rb
> +      price = build(:product_price, start_date: 2.day.ago)
Não entendi porque a linha de cima está fazendo o teste quebrar

2022-06-25 19:34 UTC, lucascda commented on spec/requests/homepage/customer_get_product_model_spec.rb
> +end
Acho que já temos um teste que testa se um usuário tenta acessar essa rota sem estar logado, na pasta de mercadores. Acha que é necessário repetir esse teste aqui?

2022-06-25 19:34 UTC, lucascda commented on spec/system/product_item/customer_changes_item_quantities_at_cart_spec.rb
> +    product.enabled!
Não é melhor passar o status enabled já na criação do objeto de produto? Acho que o teste fica mais sucinto assim.

2022-06-25 19:35 UTC, lucascda approved these changes

2022-06-25 19:36 UTC, jonathandeoliveira commented on app/controllers/product_items_controller.rb
> +  end
sempre que um usuario adicionar ou remover um  único item do carrinho a página de carrinho vai ter um redirect?

2022-06-25 19:40 UTC, jonathandeoliveira approved these changes
Acho que poderiam ter colocado as prints de como ficou no navegador nessa parte do carrinho

2022-06-25 20:22 UTC, Raifc commented on app/controllers/product_items_controller.rb
> +  end
Fizemos assim para conseguir atualizar as quantidades e mostrar para o usuário, sem isso, ao clicar no botão, o objeto é atualizado mas a view não, o redirect serve como um 'refresh' da página. Podemos ver formas melhores de fazer isso!

2022-06-25 20:24 UTC, Raifc commented on spec/models/product_price_spec.rb
> +      price = build(:product_price, start_date: 2.day.ago)
A conclusão que chegamos é que talvez isso aconteça porque a classe Time do ruby usa o fuso horário UTC por padrão, porém ainda não temos certeza, vamos continuar tentando entender o motivo disso

2022-06-25 20:24 UTC, merged

2022-06-28 11:25 UTC, marcuxyz commented on app/controllers/product_items_controller.rb
> +  end
Não vejo problemas também, uma outra opção seria usar Javascript. Mas isso pode deixar o código mais complexo!