Feature: cadastro e login de mercador
TreinaDev/e-commerce-td08-time03 pull request #9
Opened 2022-06-08 22:39 UTC by lucascda

Eu e @Raifc implementamos Log in, Log out e Sign up de um Mercador.

2022-06-09 11:51 UTC, OtavioLins approved these changes

2022-06-09 12:08 UTC, marcuxyz commented on app/models/merchant.rb
> +  validates :email, format: { with: /\A^[\w-].+@mercadores.com.br\z/ }
Gostei da validação :)

2022-06-09 12:15 UTC, marcuxyz requested changes

2022-06-09 12:15 UTC, marcuxyz commented on spec/system/merchant_logs_in_spec.rb
> +        login_as(merchant, scope: :merchant)
Como esse método comete uma ação, talvez, seja melhor coloca-lo na linha acima do `visit root_path`

2022-06-09 21:39 UTC, lucascda commented on spec/system/merchant_logs_in_spec.rb
> +        login_as(merchant, scope: :merchant)
Fizemos as alterações :)

2022-06-10 12:05 UTC, OtavioLins commented
Gente, ficou bem legal! Gostei bastante.

Só uma última coisa: lembrem de colocar na descrição do PR a issue que vocês estão fechando com o PR, tá? Para ficar organizadinho :)

2022-06-10 12:20 UTC, marcuxyz approved these changes

2022-06-10 13:06 UTC, gabdemiranda approved these changes

2022-06-10 17:39 UTC, merged